- hosts: all
  become: yes
  gather_facts: yes
  remote_user: root
  debugger: never # always | never | on_failed | on_unreachable | on_skipped
  roles:
    - epel-repository
    - os-upgrade
    # - atomic
    - collectd
    - docker
    - docker-cadvisor
    - docker-elk
    - docker-weave-scope
    - fail2ban
    # - git
    - grafana
    - graphite
    - mosh
    # - nmap
    # - postgis
    - postgres
    # - rust
    - tools
