---
- hosts: all
  sudo: yes
  gather_facts: yes
  remote_user: root
  roles:
    - epel-repository
    - os-upgrade
    - curl
    - htop
    - mc
    - mosh
    - nmap
    - postgres
    - postgis
    - rust
    - tmux
    - wget
