---

- sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: create ELK container
  docker_container:
    name: elk
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
