---

- name: add postgres repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm

- name: install postgres
  yum:
    name: postgresql96-server
    enablerepo: "epel"
  when: ansible_distribution == "CentOS"
